version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uns
    ports:
      - "9090:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pmf:
    image: momoirox/pmf
    container_name: pmf
    volumes:
      - ./images_pmf:/app/uploads/images
    restart: on-failure
    ports:
      - "8000:8000"
  
  ftn:
    image: momoirox/ftn
    container_name: ftn
    volumes:
      - ./images_ftn:/app/uploads/images
    restart: on-failure
    ports:
      - "8001:8000"
  
  pravni:
    image: momoirox/pravni
    container_name: pravni
    volumes:
      - ./images_pravni:/app/uploads/images
    restart: on-failure
    ports:
      - "8002:8000"

  uns1:
    image: momoirox/uns
    container_name: uns1
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/uns
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      
  uns2:
    image: momoirox/uns
    container_name: uns2
    restart: on-failure
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/uns
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - uns1
      - uns2
    ports:
      - "8080:80"
volumes:
  images_pmf:
  images_ftn:
  images_pravni: