version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 15s
      retries: 5
  app:
    # image: 'uns_api:latest'
    build:
      context: .
    ports:
    - "8080:8080"
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE-PLATFORM =org.hibernate.dialect.PostgreSQLDialect
   
          
